### ISSUE TITLE
v1.0 Roadmap

### ISSUE THREAD

**Issue by xarantolus** [xarantolus/MemeAssembly-vscode#9]
The extension now has a bunch of features. Since today it also integrates some of the expected stuff for a language extension -- like "Go to definition", "Go to references", Code formatting (very basic), function renaming across files (Rename symbol) etc.

But there are still some things missing before the extension can leave its pre-1.0 status. Some of them are listed here:
* [ ] Improve support for non-linux systems
    * Currently the integrated installer/updater only works for Linux
* [ ] Improve snippets
    * Currently snippets often get pasted with the wrong indentation. While this is now fixed automatically after leaving the line due to the on-typing formatter, it's still annoying
    * I have no idea why it happens, the snippets don't include any indentation
* [ ] Make sure that functions with multiple return statements are supported correctly (formatter, folding provider)
* [x] Update description
* [ ] Support upcoming SIMD modes

Maybe:
* [ ] When hovering a function call, the extension should show comments that are directly above the function definition (to serve as documentation)
* [ ] Add a [walkthrough](https://code.visualstudio.com/api/references/contribution-points#contributes.walkthroughs) that is shown on install , e.g. to prompt for compiler installation
* [ ] Automatically convert EOLs to LF (instead of CRLF), as the compiler doesn't accept CRLF (at least on Linux)
* [x] Only load files from disk if they aren't opened in an editor; if they are opened we should use the current content of the editor (for the DefinitionFinder)
* [x] Support files outside of the workspace for the "Run current file" command, even if limited (e.g. this only runs this one file without searching references)
* [x] Folding range provider for functions 
* [ ] Folding range provider for loops (somewhat problematic to implement)
* [x] Rename provider for registers (doesn't need to be that smart, just replace every text with spaces around with the new register name); maybe only for this one function the rename is done within
* [ ] Monkey labels should work across files (current implementation only searches the same file)
* [ ] Improve formatting for "Who would win" blocks, at least in certain contextes where they are not too far away/broken up by other jump labels

Unlikely:
* Debugging (would be quite cool, but probably somewhat complex) (see [this](https://github.com/Hezkore/vscode-blitzmax-support/blob/master/src/bmxruntime.ts) for an example for a custom language)
* Actual code-completion instead of snippets for commands
